---
mountPath: "hub"
mountRole: "hub-role"

global:
  hubClusterDomain: "{{ set_hubClusterDomain }}"
  clusterDomain: "{{ clusterDomain }}"

clusterGroup:
  isHubCluster: true

external-secrets:
  image:
    tag: v0.8.5-ubi
  webhook:
    image:
      tag: v0.8.5-ubi
  certController:
    image:
      tag: v0.8.5-ubi
