# Deploy vault using a helm chart
- name: Add HashiCorp Vault Helm repository
  community.kubernetes.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com
    state: present
  when: install_vault | bool

- name: Install Helm chart from HashiCorp Vault repository
  community.kubernetes.helm:
    name: hashicorp-vault
    chart_ref: vault
    chart_repo_url: https://helm.releases.hashicorp.com
    release_namespace: hashicorp-vault
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    state: present
  when: install_vault | bool

# create openshift route from template 
- name: Create openshift route from template 
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'vault-route.yaml') | from_yaml }}"
  when: install_vault | bool


# wait for vault pod to be created
- name: Wait for vault pod to be created
  community.kubernetes.k8s_info:
    kind: Pod
    api_version: v1
    namespace: hashicorp-vault
    label_selectors:
      - app.kubernetes.io/instance=hashicorp-vault
  register: vault_pod
  until: vault_pod.resources | length == 1
  retries: 30
  delay: 10
  when: install_vault | bool


- name: Remove Helm chart from HashiCorp Vault repository
  community.kubernetes.helm:
    name: hashicorp-vault
    chart_ref: vault
    chart_repo_url: https://helm.releases.hashicorp.com
    release_namespace: hashicorp-vault
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    state: absent
  ignore_errors: yes
  when: not install_vault | bool

- name: Delete openshift route from template 
  community.kubernetes.k8s:
    state: absent
    definition: "{{ lookup('template', 'vault-route.yaml') | from_yaml }}"
  when: not install_vault | bool

# wait for vault pod to be deleted
- name: Wait for vault pod to be deleted
  community.kubernetes.k8s_info:
    kind: Pod
    api_version: v1
    namespace: hashicorp-vault
    label_selectors:
      - app.kubernetes.io/instance=hashicorp-vault
  register: vault_pod
  until: vault_pod.resources | length == 0
  retries: 30
  delay: 10
  when: not install_vault | bool

- name: Remove vault
  shell: |
    oc delete ClusterRoleBinding hashicorp-vault-server-binding
  ignore_errors: yes
  when: not install_vault | bool

# delete vault namespace
- name: Delete vault namespace
  community.kubernetes.k8s:
    state: absent
    kind: Namespace
    name: hashicorp-vault
  ignore_errors: yes
  when: not install_vault | bool