# Deploy vault using a helm chart
- name: Add HashiCorp Vault Helm repository
  community.kubernetes.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com
    state: present
  when: install_vault | bool

- name: Install Helm chart from HashiCorp Vault repository
  community.kubernetes.helm:
    name: hashicorp-vault
    chart_ref: vault
    chart_repo_url: https://helm.releases.hashicorp.com
    release_namespace: hashicorp-vault
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    state: present
  when: install_vault | bool

- name: Remove Helm chart from HashiCorp Vault repository
  community.kubernetes.helm:
    name: hashicorp-vault
    chart_ref: vault
    chart_repo_url: https://helm.releases.hashicorp.com
    release_namespace: hashicorp-vault
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    state: absent
  when: install_vault | not bool

- name: Remove vault
  shell: |
    oc delete ClusterRoleBinding hashicorp-vault-server-binding
  when: install_vault | not bool