---
#- name: Run vault init tasks
#  ansible.builtin.import_tasks: vault_init.yaml
#  tags: vault_init

- name: Unseal vault
  ansible.builtin.import_tasks: vault_unseal.yaml
  tags: vault_unseal

- name: Vault secrets init
  ansible.builtin.import_tasks: vault_secrets_init.yaml
  when: vault_secrets_init | bool

- name: Vault spoke backend init
  ansible.builtin.import_tasks: vault_spokes_init.yaml
  when: vault_spokes_init | bool

- name: Load secrets
  ansible.builtin.import_tasks: push_secrets.yaml
  when: vault_push_secrets | bool
